# Demo on facts

- name: Demo on using facts
  hosts: all
  tasks:
    - name: Printing the fact
      ansible.builtin.debug:
        msg: Value of the ansible_distribution is {{ ansible_distribution }}