- name: Check Tomcat if it is running or not and start if its not running
  hosts: all
  tasks:
    - name: Checking Tomcat Status
      # ansible.builtin.shell: uptime
      ansible.builtin.shell: ps -ef | grep java | grep -v grep
      register: OUT
      ignore_errors: true

    # - name: Printing the output variable
    #   ansible.builtin.debug: 
    #     msg: "{{ OUT }}"

    # - name: Declaring the variable
    #   set_fact:
    #     STATUSCODE: "{{ OUT.rc }}"
    
    # - name: Printing the output variable
    #   ansible.builtin.debug:
    #     msg: Uptime command exit code is {{STATUSCODE}}