# Demo on privilege esclation

- name: Demonstrating Privilege Escalation
  hosts: all
  tasks:
    - name: Checking the user id
      ansible.builtin.shell: id
      register: OUT

    - name: Printing ghe OUT variable
      ansible.builtin.debug: 
        msg: "{{ OUT.stdout }}"