# Demo on installing package

- name: Demo on installing package
  hosts: all
  become: yes
  tasks:
    - name: Installing nginx
      ansible.builtin.package:
        name: nginx
        state: present