# Demo on using template

- name: Playbook to demostrate template
  hosts: all
  tasks:
    - name: Copying the systemd file
      ansible.builtin.template:
        src: env.txt
        dest: /home/centos/env.txt