- name: Installing nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Downloading and extracting the component
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Clean up of old HTML content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Copy the frontnd component which is downloaded on the remote machine nginx path
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/static/
    dest: /usr/share/nginx/html
    remote_src: yes
# If the source you're trying to copy is on the remote machine, ensureyou give the remore_src as yes

- name: Copy the proxy config
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /usr/share/nginx/html


- name: Starting nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true
