- name: Configuring the {{COMPONENT}} Repository
  ansible.builtin.copy:
    src: "{{COMPONENT}}.repo"
    dest: /etc/yum.repos.d/{{COMPONENT}}.repo

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: "{{COMPONENT}}-community-server"
    state: present


- name: Starting {{COMPONENT}}
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: true

############################################
# Use this shell approach to extract the o/p
############################################

# - name: Extracting pwd shell
#   ansible.builtin.shell: "grep 'temporary password' /var/log/mysqld.log | awk -F ' ' '{ print $NF }'"
#   register: DEFAULT_PASSWORD_S
  
# - name: Printing the default pwd
#   ansible.builtin.debug:
#    msg: "Password is {{DEFAULT_PASSWORD_S.stdout}}"

############################################

- name: Fetch the log file from the remote node
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
  register: mysql_pwd_log

- name: Capture the password and assign to a variable
  ansible.builtin.set_fact:
    DEFAULT_PASSWORD: "{{ mysql_pwd_log['content'] | b64decode | regex_findall('.*temporary password.*') | join(' ') | split(' ') | last }}"

- name: Printing the default pwd
  ansible.builtin.debug:
   msg: "Password is {{DEFAULT_PASSWORD}}"

- name: Configuring Node Name Repo
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}
# - name: Downloading and extracting the component
#   ansible.builtin.unarchive:
#     src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
#     dest: /tmp
#     remote_src: yes

# - name: Download and extract the {{COMPONENT}}
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: download

# - name: Injecting the MongoDB Schema
#   community.mongodb.mongodb_shell:
#     file: "/tmp/{{COMPONENT}}-main/{{ item }}.js"
#     idempotent: yes
#   loop:
#     - catalogue
#     - users

# - name: Configuring Node Name Repo
#   ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}