- name: Copying the systemd file Mukesh
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Restarting Mukesh {{COMPONENT}}
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: true
    daemon_reload: true