- name: Configuring Nodejs Repo {{COMPONENT}}-{{ENV}}
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Installing NodeJS on {{COMPONENT}}-{{ENV}} server
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Creating the APP User
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: Download and extract the {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Generaring Artifacts
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Configuring Service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc

- name: Configuring Node Name Repo
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}
